apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-runner-logs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/data/task-runner/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-runner-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
