tasks:
  - name: "daily_backup"
    command: "python /path/to/backup.py"
    schedule:
      type: "recurring"
      interval: "1d"
    retry:
      max_attempts: 3
      delay: 300  # 5 minutes

  - name: "weekly_report"
    command: "python /path/to/generate_report.py"
    schedule:
      type: "recurring"
      interval: "7d"
    retry:
      max_attempts: 2
      delay: 600  # 10 minutes
    dependencies: ["daily_backup"]

  - name: "one_time_task"
    command: "python /path/to/one_time_script.py"
    schedule:
      type: "one-time"
      start_time: "2024-03-25T15:00:00"
    retry:
      max_attempts: 1
      delay: 300  # 5 minutes
