name: Branch Protection

on:
  push:
    branches: [ main ]

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black isort

    - name: Run tests
      run: |
        pytest --cov=task_processor --cov-report=term-missing

    - name: Check code formatting
      run: |
        black --check task_processor tests
        isort --check-only task_processor tests
